### ISSUE TITLE
Issue with Gripper Position and Velocity Calculations with Stretch_ros2 

### ISSUE THREAD

**Issue by mkoenig2362** [hello-robot/stretch_mujoco#26]
Hello hello-robot team,
I'm combining the stretch_mujoco with the stretch_ros2 stack and ran into the following issue:
When pulling the gripper position and velocity from the StretchMujocoSimulator for the command_mobile_base_velocity_and_publish_state method inside the StretchDriver I have the problem that the calculations seem off. The published values for gripper_aperture_m range from -0.0003091475668224888 to a maximum of 0.0006818138736155684 and gripper_finger_rad between -0.000903940253866927 and 0.0019936078175893813. Without additional information it is hard to retrace the exact function of the status_to_all method and the value it expects. 
I would appreciate greatly any help or explanation that you can offer.

**Comment by hello-binit** [comment]
Closing this. Feel free to open another issue if needed.
