### ISSUE TITLE
Wrong key + format

### ISSUE THREAD

**Issue by omarrayyann** [hello-robot/stretch_mujoco#27]
![image](https://github.com/user-attachments/assets/5d462ff0-c991-4717-ace6-1844bc33af0d)
https://github.com/hello-robot/stretch_mujoco/blob/main/stretch_mujoco/robocasa_gen.py#L93C1-L93C88

I was trying to spawn it in a different location using the given key but it didn't work, using "pos" instead of "pose" fixes it. Also the value expected is not an array. I think this would be more appropriate:

robot_spawn_pose (dict): robot spawn pose {pos: "x y z", quat: "x y z w"}

**Comment by hello-binit** [comment]
Thanks @omarrayyann. It's been fixed.
