### ISSUE TITLE
D405 back ArUco flipped 180 degrees

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_mujoco#3]
The first corner of the ArUco marker on the back of the D405 camera should be the top left corner. 
![image](https://github.com/hello-robot/stretch_mujoco/assets/64861565/d0a88ec6-5491-4b07-832c-fbf55568b96e)

In this simulated Stretch, the marker is flipped 180 degrees, so the first corner ends up being the bottom right corner.
![Screenshot from 2024-06-20 00-40-55](https://github.com/hello-robot/stretch_mujoco/assets/64861565/2bb16ccf-f7e4-472a-8e61-ff86a7fdabb1)

**Comment by hello-fazil** [comment]
This is fixed in https://github.com/hello-robot/stretch_mujoco/commit/631aba360150276f5c340dbfb67a2129ec856c81
